server:
  port: 8085
  tomcat:
    max-http-form-post-size: -1

spring:
  freemarker:
    suffix: .html
  application:
    name: executeservice
  cloud:
    nacos:
      server-addr: localhost:8848  #nacos地址


