
server:
  port: 8082
  tomcat:
    max-http-form-post-size: -1


spring:
  application:
    name: problemservice
##  profiles:
##    active: dev #配置文件所属环境
  cloud:
    nacos:
      server-addr: localhost:8848  #nacos地址
#      discovery:
#        cluster-name: LKD
  #     config:
#       file-extension: yaml  #文件后缀名
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/problems_oj?serverTimezone=UTC
      username: root
      password: 1069

mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id自增
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志输出   输出到控制台
#      table-prefix: tbl_   如果表的前缀不一样需要自己添加

problemservice:  #只针对单个服务  设置
  ribbon:   #对problemservice服务设置负载均衡规则为随机
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  #配置nacos的负载均衡规则  是一种集群内的随机
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #配置Eureka的负载均衡规则
feign:
  httpclient:
    enabled: true   #支持配置HTTP client的开关
    max-connections: 200    # 最大连接数
    max-connections-per-route: 50 #单个路径最大连接
#  client:   # 配置feign的日志级别
#    config:    # 算是feign的优化
#      default:
#        loggerlevel: basic

