server:
  port: 8083

spring:
  application:
    name: discussservice
#  profiles:
#    active: dev #配置文件所属环境
  cloud:
    nacos:
      server-addr: localhost:8848  #nacos地址
#     config:
#       file-extension: yaml  #文件后缀名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/discuss_oj?serverTimezone=UTC
    username: root
    password: 1069


mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id自增
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
